---
- name: Gather System info - Test yaml
  gather_facts: false
  hosts: mysystem
  become: false
  tasks:
    - name: Gather system name
      raw: uname -a
      register: output
      
    - name: Gather System disks
      raw: df
      register: out
      tags: disk

